# Generated by Django 4.2.5 on 2024-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_patient_details_tb_profile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details_tb',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient_details_tb',
            name='mobile',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient_details_tb',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient_details_tb',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
