# Generated by Django 4.2.5 on 2024-06-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0003_patient_details_tb_email_patient_details_tb_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details_tb',
            name='languages',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
